### ISSUE TITLE
Ошибка при запуске сервера

### ISSUE THREAD

**Issue by Jok1r30** [BetaZavr/CustomNPCs_1.12.2-Unofficial#1]
Привет, catServer 1.12.2 ругается при попытке запуска мода

> java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.util.math.BlockPos
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(ClassWriter.java:1728) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassWriter.getMergedType(ClassWriter.java:1698) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.merge(Frame.java:1530) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.merge(Frame.java:1429) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1516) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:835) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412) ~[asm-debug-all-5.2.jar:5.2]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:85) [server.jar:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) [ASMTransformerWrapper$TransformerWrapper.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_332]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.buildEvents(EventSubscriptionTransformer.java:106) [server.jar:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:82) [server.jar:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) [ASMTransformerWrapper$TransformerWrapper.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_332]
	at noppes.npcs.controllers.FactionController.load(FactionController.java:178) [FactionController.class:?]
	at noppes.npcs.CustomNpcs.setAboutToStart(CustomNpcs.java:426) [CustomNpcs.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:636) [FMLModContainer.class:git-CatServer-1.12.2-090a6ffb]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:git-CatServer-1.12.2-090a6ffb]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:859) [Loader.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:294) [FMLCommonHandler.class:git-CatServer-1.12.2-090a6ffb]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:328) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]

**Comment by BetaZavr** [comment]
Спасибо за ошибку.
Модификация постоянно обновляется, так как ошибок и новинок не малое количество.
Проверяйте релиз на последние обновления.
